[package]
name = "jaeymo/Classy"
description = "A Classy is useful for ..."
version = "0.1.0"
license = "MIT"
authors = ["Jaeymo", "KashTheKing"]
registry = "https://github.com/UpliftGames/wally-index"
private = true
realm = "shared"

[dependencies]
