[package]
authors = ["Jaeymo <jaey.cyber@gmail.com>", "KashTheKing <>"]
description = "A Classy is useful for ..."
name = "jaeymo/classy"
version = "0.1.0"
license = "MIT"
exclude = ["**"]
registry = "https://github.com/UpliftGames/wally-index"
private = true
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
Signal = "stravant/goodsignal@0.3.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"