[package]
authors = ["Jaeymo <jaey.cyber@gmail.com>"]
description = "A Classy is useful because writing code for instances becomes much better!"
name = "jaeymo/classy"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
Signal = "sleitnick/signal@2.0.3"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"